### ISSUE TITLE
JS uitleg

### ISSUE THREAD

**Issue by KoopReynders** [DaanCarst/fix-the-flow-ui-events#1]
Kun je proberen uit te leggen wat deze code doet?
Graag met comments in je script file. 

https://github.com/DaanCarst/fix-the-flow-ui-events/blob/9f9f2e8248d0f559f2183eb1d83a7e54ff71c842/assets/script/main.js#L19-L24

**Comment by DaanCarst** [comment]
comments toegevoegd in JS
